version: '3.8'

services:
  clinic:
    container_name: clinic
    build: ./apps/clinic
    command: yarn start
    environment:
      PORT: ${CLINIC_SERVICE_PORT}
      DB_HOST: host.docker.internal
      REDIS_HOST: redis
    ports:
      - ${CLINIC_SERVICE_PORT}:${CLINIC_SERVICE_PORT}
    depends_on:
      - database
      - redis

  auth:
    container_name: auth
    build: ./apps/auth
    command: yarn start
    environment:
      PORT: ${AUTH_SERVICE_PORT}
      DB_HOST: host.docker.internal
      CLINIC_SERVICE_PORT: ${CLINIC_SERVICE_PORT}
      PROFILE_SERVICE_PORT: ${PROFILE_SERVICE_PORT}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    depends_on:
      - database

  profile:
    container_name: profile
    build: ./apps/profile
    command: yarn start
    environment:
      PORT: ${PROFILE_SERVICE_PORT}
      DB_HOST: host.docker.internal
    ports:
      - ${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}
    depends_on:
      - database

  database:
    container_name: pg
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinic

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
