version: '3.8'

services:
  auth:
    container_name: auth
    build: ./apps/auth
    command: yarn start
    environment:
      PORT: ${AUTH_SERVICE_PORT}
      DB_HOST: database
      CLINIC_SERVICE_GRPC_HOST: clinic
      CLINIC_SERVICE_GRPC_PORT: ${CLINIC_SERVICE_GRPC_PORT}
      PROFILE_SERVICE_GRPC_HOST: profile
      PROFILE_SERVICE_GRPC_PORT: ${PROFILE_SERVICE_GRPC_PORT}
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    depends_on:
      - database

  clinic:
    container_name: clinic
    build: ./apps/clinic
    command: yarn start
    environment:
      PORT: ${CLINIC_SERVICE_PORT}
      DB_HOST: database
      REDIS_HOST: redis
      CLINIC_SERVICE_GRPC_HOST: clinic
      CLINIC_SERVICE_GRPC_PORT: ${CLINIC_SERVICE_GRPC_PORT}
      PROFILE_SERVICE_GRPC_HOST: profile
      PROFILE_SERVICE_GRPC_PORT: ${PROFILE_SERVICE_GRPC_PORT}
    ports:
      - ${CLINIC_SERVICE_PORT}:${CLINIC_SERVICE_PORT}
    depends_on:
      - database
      - redis

  profile:
    container_name: profile
    build: ./apps/profile
    command: yarn start
    environment:
      PORT: ${PROFILE_SERVICE_PORT}
      DB_HOST: database
      CLINIC_SERVICE_GRPC_HOST: clinic
      CLINIC_SERVICE_GRPC_PORT: ${CLINIC_SERVICE_GRPC_PORT}
      PROFILE_SERVICE_GRPC_HOST: profile
      PROFILE_SERVICE_GRPC_PORT: ${PROFILE_SERVICE_GRPC_PORT}
    ports:
      - ${PROFILE_SERVICE_PORT}:${PROFILE_SERVICE_PORT}
    depends_on:
      - database

  database:
    container_name: pg
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinic

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root

  zookeeper:
    container_name: zookeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafka_ui:
    container_name: kafka_ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - 5051:8080
    depends_on:
      - kafka

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'
