version: '3.8'

services:
  clinic:
    container_name: clinic
    build: ./apps/clinic
    command: yarn start
    environment:
      - DB_HOST=host.docker.internal
      - REDIS_HOST=redis
    ports:
      - '8080:8080'
    depends_on:
      - database
      - redis

  # auth:
  #   container_name: auth
  #   build: ./apps/auth
  #   command: yarn start:dev
  #   environment:
  #     - DB_HOST=host.docker.internal
  #   ports:
  #     - '4061:4061'
  #   depends_on:
  #     - database

  database:
    container_name: pg
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clinic

  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    ports:
      - '6379:6379'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
