PORT: 4040

AUTH_SERVICE_PORT: 4040
CLINIC_SERVICE_PORT: 4041
PROFILE_SERVICE_PORT: 4042

CLINIC_SERVICE_GRPC_HOST: localhost
PROFILE_SERVICE_GRPC_HOST: localhost

CLINIC_SERVICE_GRPC_PORT: 4051
PROFILE_SERVICE_GRPC_PORT: 4052
DB_HOST: 127.0.0.1
DB_PORT: 5432
DB_USERNAME: root
DB_PASSWORD: root
DB_DATABASE: clinic

JWT_SECRET: $q^H@"f8/f}pFB"dP?XTMj~m[;25U]>Xdg7}P*Pw
JWT_EXPIRY: 3600
